import { it, expect } from 'vitest';
import { buildGrowthHiringEstimates } from '../hiring';
import { growthCourse, growthKnown } from '../lifecycle';
import { evidence, now } from './fixtures';
import type { GrowthAllocationResult } from '../types';
const course = growthCourse('Maths', 'International', 'Y10');
function setup() { const e = evidence(); e.workforce.observations = [{ id: 'current', canonicalKey: 'Tutor', observedAt: now.toISOString(), source: 'fixture', role: 'tutor', accounts: [], qualifications: [{ subject: 'Maths', curriculum: 'International', level: 'Y10', modality: 'onsite' }], offeredWindows: [{ weekday: 1, startMinute: 480, endMinute: 960, modality: 'onsite' }], leaves: [], availabilityCompleteness: 'complete', qualificationCompleteness: 'complete', completeness: 'complete', reasonCodes: [] }]; return e; }
function allocation(): GrowthAllocationResult { return { month: '2026-10', requiredHours: growthKnown(16), allocatedHours: growthKnown(0), additionalWeeklyHours: growthKnown(4), bufferedAdditionalWeeklyHours: growthKnown(4.8), observedAt: [now.toISOString()], reasonCodes: [], cells: [{ ...course, key: 'gap', month: '2026-10', weekday: 1, startMinute: 600, endMinute: 780, requiredHours: growthKnown(16), allocatedHours: growthKnown(0), additionalWeeklyHours: growthKnown(4), bufferedAdditionalWeeklyHours: growthKnown(4.8) }] }; }
it('uses matching3 hours against weekly gap4 and shows full8 hours; buffered1.6 rounds to2', () => { const r = buildGrowthHiringEstimates(setup(), [allocation()], now)[0]; expect(r.averageOfferedWeeklyHours.value).toBe(8); expect(r.averageMatchingWeeklyHours.value).toBe(3); expect(r.tutorEquivalents.value).toBeCloseTo(4 / 3); expect(r.roundedHiringEstimate.value).toBe(2); expect(r.bufferedTutorEquivalents.value).toBeCloseTo(1.6); expect(r.bufferedRoundedHiringEstimate.value).toBe(2); });
it('includes qualified unassigned known-zero tutors and dedupes linked accounts', () => { const e = setup(); e.workforce.people.push({ ...e.workforce.people[0] }, { ...e.workforce.people[0], canonicalKey: 'Zero' }); e.workforce.observations.push({ ...e.workforce.observations[0], id: 'zero', canonicalKey: 'Zero', offeredWindows: [] }); const r = buildGrowthHiringEstimates(e, [allocation()], now)[0]; expect(r.eligibleTutors).toBe(2); expect(r.knownAvailabilityTutors).toBe(2); expect(r.averageOfferedWeeklyHours.value).toBe(4); expect(r.averageMatchingWeeklyHours.value).toBe(1.5); });
it('excludes marked departures and unknown availability, and retains exact course level separation', () => { const e = setup(); e.workforce.people.push({ ...e.workforce.people[0], canonicalKey: 'Departing' }, { ...e.workforce.people[0], canonicalKey: 'Unknown' }); e.workforce.observations.push({ ...e.workforce.observations[0], canonicalKey: 'Departing', id: 'd' }, { ...e.workforce.observations[0], canonicalKey: 'Unknown', id: 'u', availabilityCompleteness: 'unknown' }); e.workforce.terminationMarks = [{ canonicalKey: 'Departing', effectiveAt: null, markedAt: now.toISOString(), status: 'pending_classes', sourceId: 'sheet' }]; const r = buildGrowthHiringEstimates(e, [allocation()], now)[0]; expect(r.eligibleTutors).toBe(2); expect(r.knownAvailabilityTutors).toBe(1); expect(r.benchmarkPersonKeys).toEqual(['Tutor']); e.workforce.observations[0].qualifications[0].level = 'Y13'; expect(buildGrowthHiringEstimates(e, [allocation()], now)[0].knownAvailabilityTutors).toBe(0); });
it('keeps zero overlap hiring unavailable and ignores individual leave/bookings in prospective benchmark', () => { const e = setup(); e.workforce.observations[0].leaves = [{ startAt: '2026-10-01T00:00:00Z', endAt: '2027-10-01T00:00:00Z', status: 'approved' }]; e.workforce.observations[0].offeredWindows[0].startMinute = 800; const r = buildGrowthHiringEstimates(e, [allocation()], now)[0]; expect(r.averageMatchingWeeklyHours.value).toBe(0); expect(r.tutorEquivalents.value).toBeNull(); expect(r.reasonCodes).toContain('HIRING_DIFFERENT_HOURS_REQUIRED'); });
