import type { WorkforceDatedObservation, WorkforcePerson, WorkforceQuery, SourceWindowResult } from '../types';
import type { WorkforceObservationInput } from '../observations';
export const query: WorkforceQuery = { from: '2026-03-01', to: '2026-10-31', viewMonth: '2026-10', role: 'all', modality: 'all' };
export const person: WorkforcePerson = { canonicalKey: 'Aria', displayName: 'Aria', role: 'tutor', rosterState: 'active', joinedAt: '2026-01-01T00:00:00Z', accounts: [{ wiseTeacherId: 't1', wiseUserId: 'u1', joinedAt: '2026-01-01T00:00:00Z', relation: 'TEACHER', modality: 'onsite' }], firstObservedAt: null, lastObservedAt: null, identityCompleteness: 'complete', reasonCodes: [] };
export function capture(key = 'a', at = '2026-10-01T03:00:00Z', end = 660, complete = true): WorkforceObservationInput {
    const observation: WorkforceDatedObservation = { id: key, canonicalKey: 'Aria', observedAt: at, source: 'wise_snapshot', role: 'tutor', accounts: person.accounts, qualifications: [{ subject: 'Maths', curriculum: 'International', level: 'G1-9', modality: 'onsite' }], offeredWindows: [{ weekday: 4, startMinute: 600, endMinute: end, modality: 'onsite' }], leaves: [], availabilityCompleteness: complete ? 'complete' : 'unknown', qualificationCompleteness: complete ? 'complete' : 'unknown', completeness: complete ? 'complete' : 'partial', reasonCodes: complete ? [] : ['availability_fetch_failed'] };
    return { sourceKey: key, snapshotId: '00000000-0000-4000-8000-000000000001', observedAt: at, people: [{ person, observation }] };
}
export function window(key = 'a', at = '2026-10-01T03:00:00Z', net = 1, complete = true): SourceWindowResult {
    const sessions = [{ wiseSessionId: 's1', wiseClassId: 'c1', classTitle: 'Maths', startAt: '2026-03-03T03:00:00Z', endAt: '2026-03-03T04:00:00Z', scheduledMinutes: 60, canonicalTutorKeys: ['Aria'], historicalBookedStudentIds: ['st1'], participantCompleteness: 'complete' as const, completeness: 'complete' as const, meetingStatus: 'ENDED', attendanceStatus: null, modality: 'onsite' as const, subject: null, curriculum: null, level: null, reasonCodes: [] }];
    const credits = [{ wiseSessionId: 's1', wiseStudentId: 'st1', netCredits: net, normalCredits: 1, evidenceStatus: 'verified' as const, sourceInterpretation: 'verified_session_charge' as const, observedAt: at, issueCodes: [] }];
    return { sourceKey: key, observedAt: at, evidence: { people: [], observations: [], sessions, tutorFacts: [], studentCredits: credits, historicalBookedParticipants: [], subjectMappings: [], terminationMarks: [], sourceCoverage: [] }, requestedWindow: { from: '2026-03-01', to: '2026-03-31' }, returnedWindow: { from: '2026-03-01', to: '2026-03-31' }, paging: { requests: 1, pagesRequested: 1, pagesReturned: 1, recordsReturned: 1 }, truncated: !complete, completeness: complete ? 'complete' : 'partial', complete, sessions, credits, contractIssues: complete ? [] : ['request_cap_exhausted'] };
}
