import type {
  AnalyticsReport,
  AnalyticsPerson,
} from "@/lib/tutor-offboarding/analytics-types";
import { confirmedDashboardFixture } from "./__tests__/fixtures";

/** Fictional browser/test data only. No names, counts or courses from production. */
export function analyticsFixture(): AnalyticsReport {
  const person = (
    key: string,
    category: AnalyticsPerson["category"],
    extra: Partial<AnalyticsPerson> = {},
  ): AnalyticsPerson => ({
    canonicalKey: key,
    displayName: key,
    category,
    currentRoster: true,
    marked: false,
    fullTime: false,
    likelihood: 20,
    lastTaughtAt: "2026-09-20T05:00:00Z",
    taughtSinceMarch: true,
    upcomingSessions30Days: 0,
    upcomingSessionsAllTime: 0,
    nextSessionAt: null,
    capabilitiesKnown: true,
    identityConflict: false,
    ...extra,
  });
  return {
    available: true,
    servedAt: "2026-10-01T07:00:00Z",
    historyStart: "2026-02-28T17:00:00Z",
    snapshotCreatedAt: "2026-10-01T06:45:00Z",
    upcomingWindowEnd: "2026-10-31T07:00:00Z",
    futureHorizonEnd: "2028-01-05T05:00:00Z",
    freshness: confirmedDashboardFixture().freshness,
    terminationSource: confirmedDashboardFixture().terminationSource!,
    totals: {
      rosterTutors: 4,
      staff: 1,
      fullTimeTutors: 0,
      historicalTeachingPeople: 4,
      historicalOffRosterPeople: 0,
      markedTutors: 1,
      markedPendingClasses: 1,
      inferredVeryLikely: 1,
      missingQualifications: 0,
      identityConflicts: 0,
      unresolvedHistoricalSessions: 0,
      missingFutureCourseIds: 0,
      conflictingSessionAssignments: 0,
    },
    turnover: {
      actualRate: null,
      unavailableReason: "Reliable hire and departure dates are not available.",
      denominator: 4,
      markedNumerator: 1,
      markedShare: 25,
      markedAndInferredNumerator: 2,
      markedAndInferredShare: 50,
    },
    monthly: [
      {
        month: "2026-03",
        teachingPeople: 4,
        endedSessions: 40,
        partial: false,
      },
      {
        month: "2026-09",
        teachingPeople: 3,
        endedSessions: 32,
        partial: false,
      },
      { month: "2026-10", teachingPeople: 1, endedSessions: 2, partial: true },
    ],
    people: [
      person("Aria", "marked_pending_classes", {
        marked: true,
        upcomingSessions30Days: 24,
        upcomingSessionsAllTime: 117,
        nextSessionAt: "2026-10-02T05:00:00Z",
      }),
      person("Bodhi", "inferred_very_likely_unmarked", { likelihood: 98 }),
      person("Cleo", "retained", {
        upcomingSessions30Days: 10,
        upcomingSessionsAllTime: 15,
      }),
      person("Dara", "unclear_unmarked", { likelihood: 58 }),
      person("Emil", "staff", {
        taughtSinceMarch: false,
        capabilitiesKnown: false,
      }),
    ],
    coverage: [
      {
        subject: "Math",
        curriculum: "British",
        level: "Y7-9",
        examPrep: null,
        currentPeople: ["Aria", "Cleo"],
        markedPeople: ["Aria"],
        inferredPeople: [],
        remainingAfterMarked: ["Cleo"],
        remainingAfterMarkedAndInferred: ["Cleo"],
        recentTeachingPeople: ["Aria", "Cleo"],
        upcomingTeachingPeople: ["Aria", "Cleo"],
      },
      {
        subject: "Computer Science",
        curriculum: "Thai",
        level: "G1-9",
        examPrep: null,
        currentPeople: ["Bodhi"],
        markedPeople: [],
        inferredPeople: ["Bodhi"],
        remainingAfterMarked: ["Bodhi"],
        remainingAfterMarkedAndInferred: [],
        recentTeachingPeople: [],
        upcomingTeachingPeople: [],
      },
    ],
    courses: [
      {
        wiseClassId: "fictional-course-1",
        title: "Aria · Small-group Math",
        wiseCourseCategory: "Y2-8/G1-7",
        personKeys: ["Aria"],
        markedPeople: ["Aria"],
        inferredPeople: [],
        upcomingSessions30Days: 24,
        upcomingSessionsAllTime: 117,
        markedUpcomingSessions30Days: 24,
        markedUpcomingSessionsAllTime: 117,
        inferredUpcomingSessions30Days: 0,
        inferredUpcomingSessionsAllTime: 0,
        firstUpcomingAt: "2026-10-02T05:00:00Z",
        lastUpcomingAt: "2028-01-05T05:00:00Z",
        endedSessionsSinceMarch: 40,
        otherHistoricalPeople: ["Cleo"],
      },
    ],
    limitations: [
      "Sheet markings may describe a planned departure, rather than a completed exit.",
      "Wise course categories describe pricing groups; academic subjects come from tutor qualifications.",
    ],
  };
}
