import type {
  WorkforceReport,
  WorkforceMetric,
  WorkforceUtilizationMetrics,
  WorkforceDrilldown,
} from "@/lib/tutor-offboarding/workforce/types";
export const metric = (
  value: number | null,
  reason = "Availability history was not retained",
): WorkforceMetric => ({
  value,
  completeness: value === null ? "unknown" : "complete",
  reasonCodes: value === null ? [reason] : [],
});
export function fixtureMetrics(
  overrides: Partial<WorkforceUtilizationMetrics> = {},
): WorkforceUtilizationMetrics {
  return {
    uniqueStudents: metric(2),
    studentBookings: metric(2),
    distinctClasses: metric(1),
    bookedHours: metric(1),
    cancelledBookings: metric(0),
    noShowBookings: metric(0),
    creditConsumedHours: metric(0.75),
    recordedTeachingHours: metric(1),
    qualifiedPeople: metric(1),
    utilizationReservedHours: metric(1),
    utilizationCreditConsumedHours: metric(0.75),
    utilizationRecordedTeachingHours: metric(1),
    offeredHours: metric(8),
    leaveHours: metric(0),
    usableHours: metric(8),
    reservedHours: metric(1),
    freeHours: metric(7),
    outsideHours: metric(0),
    overlapHours: metric(0),
    coverageHours: metric(744),
    expectedCoverageHours: metric(744),
    coveragePercent: metric(100),
    reservedUtilizationPercent: metric(12.5),
    consumedUtilizationPercent: metric(9.375),
    recordedTeachingUtilizationPercent: metric(12.5),
    ...overrides,
  };
}
/** Fictional names and evidence only; never upload production data to design services. */
export function workforceFixture(): WorkforceReport {
  const current = fixtureMetrics();
  return {
    schemaVersion: 1,
    reportRevision: "fictional-v1",
    generatedAt: "2026-10-01T05:00:00Z",
    query: {
      from: "2026-03-01",
      to: "2026-10-01",
      viewMonth: "2026-10",
      role: "all",
      modality: "all",
    },
    totals: current,
    months: ["2026-03", "2026-09", "2026-10"].map((month) => ({
      ...fixtureMetrics(
        month === "2026-10"
          ? {}
          : {
              offeredHours: metric(null),
              usableHours: metric(null),
              freeHours: metric(null),
              reservedUtilizationPercent: metric(null),
              consumedUtilizationPercent: metric(null),
              recordedTeachingUtilizationPercent: metric(null),
            },
      ),
      month,
      partialMonth: month === "2026-10",
      openingRosterCount: metric(60),
      closingRosterCount: metric(59),
      joinsCount: metric(2),
      departuresCount: metric(3),
      pendingCount: metric(2),
      turnoverPercent: metric(5),
      joinedPersonKeys: ["river"],
      departedPersonKeys: ["cleared"],
      pendingPersonKeys: ["pending"],
    })),
    subjects: ["2026-03", "2026-09", "2026-10"].flatMap((month) => [
      {
        ...fixtureMetrics(
          month !== "2026-10" ? { freeHours: metric(null) } : {},
        ),
        key: `${month}:math`,
        month,
        subject: "Mathematics",
        curriculum: null,
        level: null,
        depth: 0 as const,
        parentKey: null,
        modality: "all" as const,
      },
      {
        ...current,
        key: `${month}:igcse`,
        month,
        subject: "Mathematics",
        curriculum: "IGCSE",
        level: null,
        depth: 1 as const,
        parentKey: `${month}:math`,
        modality: "all" as const,
      },
      {
        ...current,
        key: `${month}:g10`,
        month,
        subject: "Mathematics",
        curriculum: "IGCSE",
        level: "G10",
        depth: 2 as const,
        parentKey: `${month}:igcse`,
        modality: "all" as const,
      },
      {
        ...fixtureMetrics({ freeHours: metric(0) }),
        key: `${month}:physics`,
        month,
        subject: "Physics",
        curriculum: null,
        level: null,
        depth: 0 as const,
        parentKey: null,
        modality: "all" as const,
      },
    ]),
    weekCells: [
      {
        ...current,
        key: "oct-mon-10",
        month: "2026-10",
        weekday: 1,
        startMinute: 600,
        endMinute: 630,
        coveredDates: 4,
        calendarOccurrences: 4,
        monthlyTotals: {
          creditConsumedHours: metric(3),
          freeHours: metric(28),
        },
        subject: null,
        curriculum: null,
        level: null,
        modality: "all",
      },
    ],
    people: [
      {
        ...fixtureMetrics({
          usableHours: metric(6),
          leaveHours: metric(2),
          bookedHours: metric(4),
          reservedHours: metric(4),
          recordedTeachingHours: metric(4),
          freeHours: metric(2),
          creditConsumedHours: metric(3),
          utilizationReservedHours: metric(4),
          utilizationCreditConsumedHours: metric(3),
          utilizationRecordedTeachingHours: metric(4),
          reservedUtilizationPercent: metric(400 / 6),
          consumedUtilizationPercent: metric(50),
          recordedTeachingUtilizationPercent: metric(400 / 6),
        }),
        canonicalKey: "aria",
        displayName: "Aria",
        role: "tutor",
        rosterState: "active",
        joinedAt: "2026-04-01T00:00:00Z",
        departedAt: null,
        pendingDeparture: true,
        months: [{ ...current, month: "2026-10" }],
        reasonCodes: [],
      },
      {
        ...fixtureMetrics({
          bookedHours: metric(10),
          reservedHours: metric(10),
          creditConsumedHours: metric(10),
          recordedTeachingHours: metric(10),
          freeHours: metric(0),
          utilizationReservedHours: metric(10),
          utilizationCreditConsumedHours: metric(10),
          utilizationRecordedTeachingHours: metric(10),
          reservedUtilizationPercent: metric(125),
          consumedUtilizationPercent: metric(125),
          recordedTeachingUtilizationPercent: metric(125),
          outsideHours: metric(2),
        }),
        canonicalKey: "river",
        displayName: "River",
        role: "teaching_admin",
        rosterState: "active",
        joinedAt: null,
        departedAt: null,
        pendingDeparture: false,
        months: [{ ...current, month: "2026-10" }],
        reasonCodes: ["Join date not retained"],
      },
    ],
    quality: {
      completeness: "partial",
      issueCodes: ["Historical availability unavailable"],
      exceptions: [
        {
          code: "unmapped_subject",
          entityId: "fictional-class",
          message:
            "Y2-8 is a course category; academic subject requires review.",
        },
      ],
      sourceCoverage: [
        {
          source: "Fictional retained availability",
          requestedFrom: "2026-03-01",
          requestedTo: "2026-10-01",
          returnedFrom: "2026-10-01",
          returnedTo: "2026-10-01",
          observedAt: "2026-10-01T05:00:00Z",
          pagesRequested: 1,
          pagesReturned: 1,
          recordsReturned: 2,
          truncated: false,
          completeness: "partial",
          issueCodes: ["Missing historical capacity"],
        },
      ],
    },
  };
}
export function drilldownFixture(): WorkforceDrilldown {
  const report = workforceFixture();
  return {
    query: report.query,
    reportRevision: report.reportRevision,
    kind: "person",
    key: "aria",
    people: [report.people[0]],
    contributors: {
      canonicalKeys: ["aria"],
      wiseSessionIds: ["session-example"],
      wiseClassIds: ["class-example"],
      wiseStudentIds: ["fictional-a", "fictional-b"],
      terminationSourceIds: [],
      observationIds: [],
    },
    sessions: [
      {
        wiseSessionId: "session-example",
        wiseClassId: "class-example",
        classTitle: "Physics group · fictional",
        startAt: "2026-10-01T03:00:00Z",
        endAt: "2026-10-01T04:00:00Z",
        scheduledMinutes: 60,
        canonicalTutorKeys: ["aria"],
        historicalBookedStudentIds: ["fictional-a", "fictional-b"],
        participantCompleteness: "complete",
        completeness: "complete",
        meetingStatus: "ENDED",
        attendanceStatus: "ATTENDED",
        modality: "online",
        subject: "Physics",
        curriculum: "IGCSE",
        level: "G10",
        reasonCodes: [],
      },
    ],
    observations: [],
    exceptions: [],
    nextCursor: null,
  };
}
